[package]
name = "raytracer3"
version = "0.1.0"
authors = ["mike stedman <barbeque@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cgmath = "*"
rand = "*"
clap = "*"
rayon = "*"
image = "*"
